import { ArrowLeft } from "lucide-react";

// ═══════════════════════════════════════════════════════════════════════════
// Terms of Service — Legal Framework for The Storage-Network
// ═══════════════════════════════════════════════════════════════════════════

export const metadata = {
  title: "Terms of Service | The Storage-Network",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-stone-300">
      <header className="border-b border-slate-800 bg-slate-900 px-4 py-4">
        <div className="mx-auto flex max-w-2xl items-center gap-3">
          <a
            href="/"
            className="rounded-lg p-2 text-stone-400 transition-colors hover:bg-slate-800 hover:text-white"
          >
            <ArrowLeft className="h-5 w-5" />
          </a>
          <h1 className="text-sm font-bold uppercase tracking-wider text-white">
            Terms of Service
          </h1>
        </div>
      </header>

      <main className="mx-auto max-w-2xl px-4 py-8">
        <div className="prose prose-invert prose-sm max-w-none">
          <p className="text-xs text-stone-500">
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">1. Nature of Service</h2>
          <p>
            The Storage-Network (&quot;Platform,&quot; &quot;we,&quot; &quot;us&quot;) is a technology
            marketplace that connects homeowners and property managers (&quot;Customers&quot;) with
            independent contractor installers (&quot;Installers&quot;) who provide custom tote-based
            garage storage solutions.
          </p>
          <p>
            The Platform facilitates discovery, scheduling, and payment processing between Customers
            and Installers. <strong>The Storage-Network is not a construction company, general
            contractor, or employer of Installers.</strong> All installation services are performed
            by independent contractors who maintain their own business licenses, insurance, and tools.
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">2. User Accounts</h2>
          <p>
            You must provide accurate, current, and complete information when creating an account.
            You are responsible for maintaining the confidentiality of your login credentials and
            for all activities that occur under your account. Notify us immediately of any
            unauthorized use.
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">3. Booking &amp; Payment Terms</h2>
          <p>
            When a Customer books an installation through the Platform, a deposit of 15% of the
            quoted total is collected at the time of booking. This deposit is processed via Stripe
            and is subject to Stripe&apos;s terms of service.
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>The remaining 85% balance is due upon completion of the installation.</li>
            <li>A platform service fee of up to 15% is applied to each transaction, depending on the installer&apos;s plan and lead source.</li>
            <li>All prices quoted through the configurator are estimates; final pricing may vary
              based on site conditions.</li>
          </ul>

          <h2 className="mt-8 text-lg font-bold text-white">4. Cancellation &amp; Refund Policy</h2>
          <p>
            Customers may cancel a booking with a full deposit refund if cancellation is made
            at least <strong>24 hours before the scheduled installation date</strong>. Cancellations
            made less than 24 hours before the scheduled date forfeit the deposit.
          </p>
          <p>
            Installers who cancel within 24 hours of a confirmed booking may be subject to
            account penalties, including temporary suspension from the Platform.
          </p>

          <h2 id="installation" className="mt-8 text-lg font-bold text-white">
            5. Installation Agreement &amp; Workmanship Warranty
          </h2>
          <p>
            All Installers on The Storage-Network agree to the following standards:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>30-Day Workmanship Warranty:</strong> Installers guarantee their work for
              30 days from the date of installation. If a structural defect arises due to
              installation error within this period, the Installer will return to correct the
              issue at no additional charge.
            </li>
            <li>
              <strong>Material Accuracy:</strong> Installers will use materials consistent with
              the build plan generated by the Platform configurator.
            </li>
            <li>
              <strong>Professional Conduct:</strong> Installers will arrive on time, communicate
              proactively about delays, and leave the work area clean upon completion.
            </li>
          </ul>

          <h2 className="mt-8 text-lg font-bold text-white">6. Limitation of Liability</h2>
          <p>
            <strong>The Storage-Network is a technology platform and assumes no liability for
            property damage, personal injury, or any loss arising from the installation services
            performed by Installers.</strong> The Installer is solely responsible for the quality,
            safety, and compliance of their work.
          </p>
          <p>
            To the maximum extent permitted by law, The Storage-Network&apos;s total liability
            for any claim related to the Platform shall not exceed the amount of fees paid by
            the claimant to the Platform in the 12 months preceding the claim.
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">7. Contractor Agreement</h2>
          <p>
            By joining The Storage-Network as an Installer, you acknowledge and agree that:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>You are an independent contractor, not an employee of The Storage-Network.</li>
            <li>You are responsible for your own taxes, insurance, and business compliance.</li>
            <li>You will maintain appropriate general liability insurance for the services you provide.</li>
            <li>You grant The Storage-Network a non-exclusive license to use your business name,
              logo, and service area information for marketing purposes on the Platform.</li>
            <li>You will honor the 30-day workmanship warranty described in Section 5.</li>
          </ul>

          <h2 className="mt-8 text-lg font-bold text-white">8. Intellectual Property</h2>
          <p>
            All content on the Platform, including the build configurator, 3D visualizer,
            cut plan algorithms, and brand assets, is the property of Storage-Network.app and
            is protected by applicable intellectual property laws. You may not reproduce,
            distribute, or create derivative works without written permission.
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">9. Dispute Resolution</h2>
          <p>
            Any disputes arising from the use of the Platform shall be resolved through
            binding arbitration in accordance with the rules of the American Arbitration
            Association. The arbitration shall take place in the state of Nebraska.
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">10. Modifications</h2>
          <p>
            We reserve the right to modify these Terms at any time. Material changes will
            be communicated via email or a prominent notice on the Platform. Continued use
            of the Platform after changes constitutes acceptance of the updated Terms.
          </p>

          <h2 className="mt-8 text-lg font-bold text-white">11. Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:support@storage-network.app" className="text-yellow-400 hover:underline">
              support@storage-network.app
            </a>.
          </p>

          <div className="mt-12 rounded-xl border border-slate-800 bg-slate-900 p-4 text-center">
            <p className="text-xs text-stone-500">
              &copy; {new Date().getFullYear()} Storage-Network.app. All rights reserved.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
